services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommjava
      # MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - keycloak-network
    ports:
      - 3306:3306
    volumes:
      #  - ./dbdata:/var/lib/mysql/
      - ./basedata.sql:/docker-entrypoint-initdb.d/base.sql

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    ports:
      - 8281:8080
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: ecommjava
      DB_USER: root
      DB_PASSWORD: root
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    networks:
      - keycloak-network
    depends_on:
      - mysql
    command: start-dev

networks:
  keycloak-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local